# pytorch_lightning==1.8.0
seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: CC_seed42_BCE_128_5e-07_1.40625deg_range24
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: WildfireSpreadTS_WFB
      log_model: true
      experiment: null
      prefix: ''
      job_type: null
      config: null
      entity: null
      reinit: null
      tags: null
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      fork_from: null
      resume_from: null
      settings: null
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val/loss
      min_delta: 0.0
      patience: 100
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: pytorch_lightning.callbacks.RichModelSummary
    init_args:
      max_depth: -1
  - class_path: pytorch_lightning.callbacks.RichProgressBar
    init_args:
      refresh_rate: 1
      leave: false
      theme:
        description: white
        progress_bar: '#6206E0'
        progress_bar_finished: '#6206E0'
        progress_bar_pulse: '#6206E0'
        batch_progress: white
        time: grey54
        processing_speed: grey70
        metrics: white
      console_kwargs: null
  default_root_dir: /home/as26840@ens.ad.etsmtl.ca/repos/Wildfire_Bench/logs/WildfireSpreadTS
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: '1'
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 2
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: ddp
  sync_batchnorm: true
  precision: 16
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
model:
  net:
    class_path: models.climax.arch.ClimaX
    init_args:
      default_vars:
      - VIIRS band M11
      - VIIRS band I2
      - VIIRS band I1
      - NDVI
      - EVI2
      - total precipitation
      - wind speed
      - wind direction
      - minimum temperature
      - maximum temperature
      - energy release component
      - specific humidity
      - slope
      - aspect
      - elevation
      - pdsi
      - Landcover_Type1
      - forecast total_precipitation
      - forecast wind speed
      - forecast wind direction
      - forecast temperature
      - forecast specific humidity
      - active fire binary
      - active fire detection times
      - Landcover_Type1 onehot_1
      - Landcover_Type1 onehot_2
      - Landcover_Type1 onehot_3
      - Landcover_Type1 onehot_4
      - Landcover_Type1 onehot_5
      - Landcover_Type1 onehot_6
      - Landcover_Type1 onehot_7
      - Landcover_Type1 onehot_8
      - Landcover_Type1 onehot_9
      - Landcover_Type1 onehot_10
      - Landcover_Type1 onehot_11
      - Landcover_Type1 onehot_12
      - Landcover_Type1 onehot_13
      - Landcover_Type1 onehot_14
      - Landcover_Type1 onehot_15
      - Landcover_Type1 onehot_16
      img_size:
      - 128
      - 128
      output_size:
      - 128
      - 128
      patch_size: 2
      output_patch_size: 1
      embed_dim: 1024
      depth: 8
      decoder_depth: 2
      num_heads: 16
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1
      parallel_patch_embed: false
      freeze_encoder: false
  pretrained_res: 1.40625deg
  pretrained_path: /home/aamer98/projects/def-ebrahimi/aamer98/repos/Wildfire_Bench/weights/1.40625deg.ckpt
  experiment: CC_seed42_BCE_128_5e-07_1.40625deg_range24
  loss_function: BCE
  lr: 5.0e-07
  beta_1: 0.9
  beta_2: 0.99
  weight_decay: 1.0e-05
  warmup_epochs: 10000
  max_epochs: 100000
  warmup_start_lr: 1.0e-08
  eta_min: 1.0e-08
  pos_class_weight: 236
  crop_side_length: 128
  freeze_encoder: false
data:
  root_dir: /home/aamer98/projects/def-ebrahimi/aamer98/data/wildfirespreadTS_unitTest
  variables:
  - VIIRS band M11
  - VIIRS band I2
  - VIIRS band I1
  - NDVI
  - EVI2
  - total precipitation
  - wind speed
  - wind direction
  - minimum temperature
  - maximum temperature
  - energy release component
  - specific humidity
  - slope
  - aspect
  - elevation
  - pdsi
  - Landcover_Type1
  - forecast total_precipitation
  - forecast wind speed
  - forecast wind direction
  - forecast temperature
  - forecast specific humidity
  - active fire binary
  - active fire detection times
  - Landcover_Type1 onehot_1
  - Landcover_Type1 onehot_2
  - Landcover_Type1 onehot_3
  - Landcover_Type1 onehot_4
  - Landcover_Type1 onehot_5
  - Landcover_Type1 onehot_6
  - Landcover_Type1 onehot_7
  - Landcover_Type1 onehot_8
  - Landcover_Type1 onehot_9
  - Landcover_Type1 onehot_10
  - Landcover_Type1 onehot_11
  - Landcover_Type1 onehot_12
  - Landcover_Type1 onehot_13
  - Landcover_Type1 onehot_14
  - Landcover_Type1 onehot_15
  - Landcover_Type1 onehot_16
  n_leading_observations: 1
  n_leading_observations_test_adjustment: 1
  load_from_hdf5: true
  remove_duplicate_features: false
  features_to_keep: null
  return_doy: false
  data_fold_id: 0
  out_variables:
  - active fire binary
  predict_range: 24
  hrs_each_step: 1
  batch_size: 2
  num_workers: 1
  pin_memory: false
my_model_checkpoint:
  dirpath: /home/as26840@ens.ad.etsmtl.ca/repos/Wildfire_Bench/logs/WildfireSpreadTS/checkpoints
  filename: best_CC_seed42_BCE_128_5e-07_1.40625deg_range24
  monitor: val/loss
  verbose: false
  save_last: true
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
